All main functions implemented
vastlimits/uberAgent-ESA-Sysmon-Converter pull request #2
Opened 2021-08-06 18:03 UTC by DenysTsi

2021-08-09 09:18 UTC, DieterSchmitz requested changes

2021-08-09 09:18 UTC, DieterSchmitz commented on vl.Sysmon.Converter/Domain/ConvertEntity.cs
> +            Log.Warning(Constants.RuleNotSupportedTemplate, itemName, "uberAgent currently does not support reading the integrity level.");
@DenysTsi Integrity level passt hier wohl nicht

2021-08-09 09:18 UTC, DieterSchmitz commented on vl.Sysmon.Converter/Domain/EventData/DNSQuery.cs
> +                     case SysmonEventFilteringRuleGroupDnsQueryImage c:
@DenysTsi Das hier kenne ich nicht. Was macht das "c" am Ende der case Anweisung? Ist das ein C# feature?

2021-08-09 09:18 UTC, DieterSchmitz commented on vl.Sysmon.Converter/Domain/SysmonConfig.cs
> +﻿//
@DenysTsi 7000 Zeilen??? Das habe ich nur oberflächlich gecheckt

2021-08-09 11:16 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/SysmonConfig.cs
> +﻿//
@DieterSchmitz Is generated code, you do not need to look at it. 😁

2021-08-09 11:21 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/EventData/DNSQuery.cs
> +                     case SysmonEventFilteringRuleGroupDnsQueryImage c:
@DieterSchmitz item is of type 'object' and we check if the respective object is of type X and **c** is the variable definition.

2021-08-09 11:23 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/ConvertEntity.cs
> +            Log.Warning(Constants.RuleNotSupportedTemplate, itemName, "uberAgent currently does not support reading the integrity level.");
Thanks, it's fixed.

2021-08-09 11:24 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/Activity/Registry.cs
> +            Log.Error(ex, $"Failure to convert rules for ProcessStartup.");
@DieterSchmitz That's right, it's fixed.

2021-08-09 11:25 UTC, DenysTsi commented on vl.Core/Domain/Activity/Hive.cs
> +      All
@DieterSchmitz Have right with both, currently A and WC are not yet interesting.

2021-08-09 11:41 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/ConvertEntity.cs
> +            Tag = monitoringRule.Name,
@DieterSchmitz A **RuleGroup** can only have one name, the rules then have their own names, but since we are combining a whole RuleGroup into one rule, I can't just take any name from the rules for the tag.
So I decided, if there is one name for the RuleGroup, it is the name and the tag.

2021-08-09 11:42 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/Activity/Registry.cs
> +                     break;
@DieterSchmitz At Sysmon there are only the 4 EventTypes.

2021-08-09 11:50 UTC, DenysTsi commented on vl.Core/Domain/Extensions/HiveExtensions.cs
> +            Hive.Unknown => "*",
@DieterSchmitz I have now replaced this with an exception.

2021-08-09 13:12 UTC, DieterSchmitz approved these changes

2021-08-11 10:58 UTC, svnscha requested changes
I have left a couple of comments and suggestions. I would really change these things especially the Attribute suggestion to keep this easily maintainable in future events and fields.

Also, what I am really missing in this code are comments. Especially all the conversion things should add comments about the Sysmon fields including value examples, etc. This makes it easier to follow the implementation of conversions and string trimming and other operations that I have seen.

2021-08-11 10:58 UTC, svnscha commented on vl.Core/Domain/Activity/ActivityMonitoringRuleSerializer.cs
> +         RuleName = Detect Backslashy
@DenysTsi This comment still needed?

2021-08-11 10:58 UTC, svnscha commented on vl.Core/Domain/Activity/ActivityMonitoringRuleSerializer.cs
> +                  rule.Tag= "A-Sysmon-converted-rule";
Tags should be lowercase. Also, please fixup the rule.Tag= (whitespace).

2021-08-11 10:58 UTC, svnscha commented on vl.Core/Domain/Extensions/EventTypeExtensions.cs
> +      public static string ToActivityMonitoringString(this EventType eventType)
How about rename this function to `ToActivityEventName` ?

2021-08-11 10:58 UTC, svnscha commented on vl.Core/Domain/Extensions/HiveExtensions.cs
> +      public static string ToActivityMonitoringHive(this Hive hive)
How about `ToActivityRegistryHive` ?

2021-08-11 10:58 UTC, svnscha commented on vl.Sysmon.Converter/Domain/Activity/ProcessNetwork.cs
> +      public static ActivityMonitoringRule[] ConvertRules(
Instead of raw arrays I would suggest returning `IEnumerable<ActivityMonitoringRule>` and return `Enumerable.Empty<ActivityMonitoringRule>()` for empty ones.

2021-08-11 10:58 UTC, svnscha commented on vl.Sysmon.Converter/Domain/Activity/ProcessStartup.cs
> +      public static ActivityMonitoringRule[] ConvertRules(
Please use IEnumerable here, too.

2021-08-11 10:58 UTC, svnscha commented on vl.Sysmon.Converter/Domain/Activity/ProcessStop.cs
> +      public static ActivityMonitoringRule[] ConvertRules(
Please use IEnumerable here, too.

2021-08-11 10:58 UTC, svnscha commented on vl.Sysmon.Converter/Domain/Activity/Registry.cs
> +      public static ActivityMonitoringRule[] ConvertRules(
Please use IEnumerable here, too.

2021-08-11 10:58 UTC, svnscha commented on vl.Sysmon.Converter/Domain/ConvertEntity.cs
> +      private static SysmonConditionBase CreateSysmonBaseCondition(object item)
@DenysTsi I do not like this implementation. I would prefer a more generic version of this method.  Also, why do you check most `itemName` with `EndsWith` ?

I would like to see something like this:

```cs
[TranslateField("User", "Process.User")]
[TranslateField("ParentProcessId", "Parent.Id")]
[TranslateField("ProcessId", "Process:id")]
// etc
private static SysmonConditionBase CreateSysmonBaseCondition()
{
}
```

Most fields are easily translated by just changing the name to uberAgent field names.  Special value conversion could take a third parameter with a function name that performs the actual conversion.

If the translatable field is unknown (or must be determined) such as `Parent.Path` or `Parent.Name`  or any other field that equals a Path or Name I would simply add another attribute that inherits the suggested `TranslateField` attribute to return the actual field name dynamically.

2021-08-11 10:58 UTC, svnscha commented on vl.Sysmon.Converter/Domain/ConvertEntity.cs
> +      private static bool CheckNotSupported(string itemName)
Same as above, I treat anything not handled as not supported and for some of these we have a custom log message I would just add another attribute such as `[NotSupportedField("FieldName", "Custom message")`.

2021-08-11 10:58 UTC, svnscha commented on vl.Sysmon.Converter/Domain/EventData/DNSQuery.cs
> +                        uberAgentMetricField = "DnsRequest";
@DenysTsi Shouldn't this use a constant?

2021-08-11 20:41 UTC, DenysTsi commented on vl.Core/Domain/Activity/ActivityMonitoringRuleSerializer.cs
> +         RuleName = Detect Backslashy
@svnscha You wanted to have some comments on the structure, this comment represents the structure to which it will be serialized. 😁

2021-08-11 20:43 UTC, DenysTsi commented on vl.Core/Domain/Extensions/EventTypeExtensions.cs
> +      public static string ToActivityMonitoringString(this EventType eventType)
@svnscha Good idea, is changed.

2021-08-11 20:44 UTC, DenysTsi commented on vl.Core/Domain/Extensions/HiveExtensions.cs
> +      public static string ToActivityMonitoringHive(this Hive hive)
Changed.

2021-08-11 20:52 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/EventData/DNSQuery.cs
> +                        uberAgentMetricField = "DnsRequest";
@svnscha yes, changed.

2021-08-12 14:35 UTC, DenysTsi commented on vl.Sysmon.Converter/Domain/ConvertEntity.cs
> +      private static SysmonConditionBase CreateSysmonBaseCondition(object item)
@svnscha thanks, changed it to attributes and replaced also the NotSupported check with attributes.

2021-08-13 08:54 UTC, svnscha requested changes
Just a minor change, then it's good.

2021-08-13 08:54 UTC, svnscha commented on vl.Core/Domain/Attributes/TransformFieldAttribute.cs
> +   public abstract class TransformFieldBaseAttribute : Attribute
Please refactor the classes to separate files.

2021-08-13 14:18 UTC, DenysTsi commented on vl.Core/Domain/Attributes/TransformFieldAttribute.cs
> +   public abstract class TransformFieldBaseAttribute : Attribute
@svnscha ah yes, done.

2021-08-16 14:11 UTC, merged