Possibility to specify the rules to be converted
vastlimits/uberAgent-ESA-Sysmon-Converter pull request #5
Opened 2021-11-16 16:39 UTC by DenysTsi

Added possibility to specify the rules to be converted

2021-11-16 20:26 UTC, svnscha requested changes

2021-11-16 20:26 UTC, svnscha commented on vl.Core/Domain/Activity/SysmonEventId.cs
> +}
Please use fixed constants as they don't change.

2021-11-16 20:26 UTC, svnscha commented on vl.Sysmon.Converter/Program.cs
> +                     case SysmonEventId.ProcessTampering:
How about implementing Process Tampering? ;-)

2021-11-18 15:49 UTC, DenysTsi commented on vl.Core/Domain/Activity/SysmonEventId.cs
> +}
Had also thought about it, is adjusted.

2021-11-18 15:49 UTC, DenysTsi commented on vl.Sysmon.Converter/Program.cs
> +                     case SysmonEventId.ProcessTampering:
@svnscha in another feature branch, thanks.

2021-11-18 15:49 UTC, merged